
GET http://localhost:3000/btcaddr

###
POST http://localhost:3000/btcaddr
Content-Type: application/json

{
    "addr": "13Js7D3q4KvfSqgKN8LpNq57gcahrVc5JZ",
    "sig": "H+/grsJ9K2XtbWAwAwpkypVpuRP++Grm4H+mycTUBcBbJ77CVEsU54rdSFJoJMngh0NtqDEF4tnojMd/aRH6F18="
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "ajit",
    "password": "bubbcity"
}
